default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: actioncable_chat_development
  username: nickvyrko
  #username: actioncable_chat
  #password:
  #host: localhost
  #port: 5432

test:
  <<: *default
  database: actioncable_chat_test

production:
  <<: *default
  database: actioncable_chat_production
  username: actioncable_chat
  password: <%= ENV['ACTIONCABLE_CHAT_DATABASE_PASSWORD'] %>
